package com.flightaware.flightxml.soap.flightxml2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * FlightXML2 Web Services
 *
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-12T17:01:14.426-05:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "FlightXML2", 
                  wsdlLocation = "http://flightxml.flightaware.com/soap/FlightXML2/wsdl",
                  targetNamespace = "http://flightxml.flightaware.com/soap/FlightXML2") 
public class FlightXML2 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://flightxml.flightaware.com/soap/FlightXML2", "FlightXML2");
    public final static QName FlightXML2Soap = new QName("http://flightxml.flightaware.com/soap/FlightXML2", "FlightXML2Soap");
    static {
        URL url = null;
        try {
            url = new URL("http://flightxml.flightaware.com/soap/FlightXML2/wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FlightXML2.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://flightxml.flightaware.com/soap/FlightXML2/wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FlightXML2(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FlightXML2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightXML2() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FlightXML2(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FlightXML2(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FlightXML2(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns FlightXML2Soap
     */
    @WebEndpoint(name = "FlightXML2Soap")
    public FlightXML2Soap getFlightXML2Soap() {
        return super.getPort(FlightXML2Soap, FlightXML2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightXML2Soap
     */
    @WebEndpoint(name = "FlightXML2Soap")
    public FlightXML2Soap getFlightXML2Soap(WebServiceFeature... features) {
        return super.getPort(FlightXML2Soap, FlightXML2Soap.class, features);
    }

}
